### ISSUE TITLE
插件冲突

### ISSUE THREAD

**Issue by saxon134** [yuan1809/tencent_live_flutter#1]
该插件跟下面的插件一同使用会有冲突，编译不过。
video_player: ^0.10.11+2

**Comment by saxon134** [comment]
腾讯直播SDK和video_player都引用了exoplayer，冲突了。
我的临时方案：
下载腾讯直播jar到本地
修改tencent_live_flutter的build.grandle
api 'com.tencent.liteavsdk:LiteAVSDK_Smart:latest.release'
改为：
implementation fileTree(dir:'libs',include:['*.jar'])

**Comment by softmaxs** [comment]
克隆此项目根据文档运行出现以下错误
I/testArr ( 5963): 获取数据
W/Native-LiteAV( 5963): load library txffmpeg from system path
W/Native-LiteAV( 5963): load library : java.lang.UnsatisfiedLinkError: dlopen failed: library "libtxffmpeg.so" not found
W/Native-LiteAV( 5963): load library txffmpeg false
W/Native-LiteAV( 5963): load library traeimp-rtmp from system path
W/Native-LiteAV( 5963): load library : java.lang.UnsatisfiedLinkError: dlopen failed: library "libtraeimp-rtmp.so" not found
W/Native-LiteAV( 5963): load library traeimp-rtmp false
W/Native-LiteAV( 5963): load library liteavsdk from system path
W/Native-LiteAV( 5963): load library : java.lang.UnsatisfiedLinkError: dlopen failed: library "libliteavsdk.so" not found

本人对原生不熟悉，望指点！

运行环境：ubuntu20；android studio 4.0.1；android SDK版本android 10.0;flutter版本1.9.0；dart版本2.9.0

@saxon134

**Comment by saxon134** [comment]
看错误信息，应该是腾讯的SDK没下载，或者路径不对吧。
检查一下看看吧
